hashMap
charzik/ALGO pull request #2
Opened 2018-03-13 13:04 UTC by charzik

2018-03-13 14:48 UTC, ifsmirnov requested changes

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    HashMap(Hash hasher = Hash()) : hasher(hasher) {
Лучше привыкать писать Hash{}, это универсальнее.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    HashMap(Iterator left, Iterator right, Hash hasher = Hash()) : hasher(hasher) {
Лучше first, last, как в STL.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    HashMap(const std::initializer_list<std::pair<KeyType, ValueType>>& list,
initializer_list можно принимать по значению.

В этом конструкторе можно вызвать предыдущий:

```
: HashMap(list.begin(), list.end(), hasher) {}
```

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +        for (auto x : other)
const auto&

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +        if (this == &other)
Лучше std::addressof

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    void erase(const KeyType& el) {
element/value. Не надо таких сокращений.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +        } else {
Зачем else, ты уже return сделал.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +        size_t i = hasher(el) % table.size();
Слишком много копипасты между этим методом и следующим. Можно, например, сделать служебную функцию, которая возвращает номер ячейки или какое-то зарезервированное значение, если ключ не найден, и вызывать её.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +            return (find(key))->second;
А если сделать так, чтобы insert возвращал итератор, второй раз find вызывать будет не нужно.

insert({key, ValueType{}});

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +        return (find(key))->second;
Зачем ещё один find? Уже есть итератор.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    std::list<std::pair<const KeyType, ValueType>> lst;
Лучше где-нибудь в начале сделать typedef на этот тип, он слишком часто используется.

Не надо сокращать list до lst.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    const size_t MAX_WAY = 5, defaultSize = 8;
1) пиши объявления на разных строчках
2) почему одна константа называется ВОТ_ТАК, а другая вотТак?
3) MAX_WAY -- совсем непонятное название.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    size_t way, curSize;
1) Что такое way?
2) НИКОГДА НЕ НАДО ИСПОЛЬЗОВАТЬ В КОДЕ cur. В конце имён полей класса можно ставить подчёркивание.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +        std::vector<std::pair<const KeyType, ValueType>> tmp;
Вместо служебного вектора можно смувать тот же лист:

```
auto copy = std::move(lst);
```

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    void recalc() {
Тогда уж rebuild.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    void insert(const std::pair<const KeyType, ValueType>& el, bool fl = true) {
Что значит переменная fl?

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +            while (it != lst.end() && hasher(it->first) % table.size() == i) {
Вложенность кода слишком большая, читается тяжело. Нужно упростить логику.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +            while (it != lst.end() && hasher(it->first) % table.size() == i) {
Кажется, общий код отсюда и из find можно вынести в отдельную функцию.

2018-03-13 14:48 UTC, ifsmirnov commented on hashMap.cpp
> +    void normalize() {
Чем эта функция заслуживает своё название? Непонятно, что именно она _нормализует_.

2018-03-17 11:27 UTC, charzik commented on hashMap.cpp
> +        size_t i = hasher(el) % table.size();
Я не совсем понимаю как это делать. У нас же один метод будет константным а другой нет. Если я вынесу общий кусок кода у меня же компилятор будет ругаться.

2018-04-04 21:05 UTC, merged